version: "3.7"

services:
    emiga-sss:
        restart: always
        build: .
        volumes:
            - .:/build
        networks:
            - nginx
        env_file:
            - ./.env
        environment:
            - PORT=3000
            - HOSTNAME=emiga-sss
            - NODE_ENV=production

    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
        networks:
            - nginx
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - emiga-sss
        depends_on:
            - emiga-sss

networks:
    nginx:
        driver: bridge